---
driver:
  name: docker
  use_sudo: false
  volume: "/var/run/docker.sock:/var/run/docker.sock"  # Docker-in-docker

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-16.04

suites:
  - name: default
    run_list:
      - recipe[docker-base]
